# -*- coding: utf-8 -*-
"""CSE_Project_Maanali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gh2UlVSIQBm9L4ldKYl0fVAhQey7DUhb
"""

# Simple Food Ordering App

# Fruit menu with prices
menu = {
    "Apple": 30,
    "Banana": 10,
    "Grapes": 50,
    "Mango": 40,
    "Orange": 20,
    "Pineapple": 60,
    "Papaya": 35,
    "Watermelon": 80,
    "Strawberry": 90,
    "Blueberry": 120,
    "Kiwi": 45,
    "Pomegranate": 70,
    "Guava": 25,
    "Peach": 55,
    "Cherry": 110
}

print("===== Welcome to the Fruit Ordering App =====")
print("\nAvailable Fruits and Prices:")
for fruit, price in menu.items():
    print(f"{fruit} - Rs {price}")

cart = {}  # to store selected items and quantities

while True:
    choice = input("\nEnter a fruit name to add to cart (or type 'done' to finish): ").title()

    if choice == "Done":
        break

    # Check if fruit exists
    if choice in menu:
        qty = int(input(f"Enter quantity of {choice}: "))
        if choice in cart:
            cart[choice] += qty
        else:
            cart[choice] = qty
        print(f"{qty} {choice}(s) added to cart!")

    else:
        print("Invalid fruit! Please select from the menu.")

# ------- BILL GENERATION -------
print("\n========== FINAL BILL ==========")
total = 0

for fruit, qty in cart.items():
    price = menu[fruit]
    cost = price * qty
    total += cost
    print(f"{fruit} × {qty} = Rs {cost}")

print("--------------------------------")
print(f"Total Amount: Rs {total}")
print("================================")
print("Thank you for your order!")

# Simple Food Ordering App - Enhanced Version
# Fruit menu with prices
menu = {
    "Apple": 30,
    "Banana": 10,
    "Grapes": 50,
    "Mango": 40,
    "Orange": 20,
    "Pineapple": 60,
    "Papaya": 35,
    "Watermelon": 80,
    "Strawberry": 90,
    "Blueberry": 120,
    "Kiwi": 45,
    "Pomegranate": 70,
    "Guava": 25,
    "Peach": 55,
    "Cherry": 110
}

print("===== Welcome to the Fruit Ordering App =====")
print("\nAvailable Fruits and Prices:")
for fruit, price in menu.items():
    print(f"{fruit} - Rs {price}")

cart = {}  # to store selected items and quantities

while True:
    choice = input("\nEnter a fruit name to add to cart (or type 'done' to finish): ").strip().title()

    if choice == "Done":
        break

    # Check if fruit exists
    if choice in menu:
        while True:
            try:
                qty_input = input(f"Enter quantity of {choice}: ").strip()
                qty = int(qty_input)

                if qty <= 0:
                    print("❌ Quantity must be a positive number! Please try again.")
                    continue
                elif qty > 1000:
                    print("⚠️ Warning: Large quantity! Please confirm it's correct.")
                    confirm = input("Continue? (yes/no): ").strip().lower()
                    if confirm not in ['yes', 'y']:
                        continue

                # Add to cart
                if choice in cart:
                    cart[choice] += qty
                else:
                    cart[choice] = qty
                print(f"✓ {qty} {choice}(s) added to cart!")
                break

            except ValueError:
                print("❌ Invalid input! Please enter a valid number.")
            except KeyboardInterrupt:
                print("\n\n⚠️ Order cancelled by user.")
                exit()
    else:
        print("❌ Invalid fruit! Please select from the menu above.")

# ------- BILL GENERATION -------
print("\n========== FINAL BILL ==========")

if not cart:
    print("Your cart is empty. No items ordered.")
else:
    total = 0
    print(f"{'Item':<15} {'Qty':<8} {'Price':<10} {'Cost':<10}")
    print("-" * 45)

    for fruit, qty in cart.items():
        price = menu[fruit]
        cost = price * qty
        total += cost
        print(f"{fruit:<15} {qty:<8} Rs {price:<7} Rs {cost:<7}")

    print("-" * 45)
    print(f"{'TOTAL':<32} Rs {total}")

print("=" * 45)
print("Thank you for your order! 🍎🍌🍇")
print("=" * 45)